repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: "tests/"
        types: [python]
        args: ["-d C0411,C0209,W0511"]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        exclude: "tests/"
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        exclude: "tests/"
        language: system
        types: [python]
        args: ["--max-line-length=88", "--ignore=E203,W503,S101,tests"]
